version: "3.7"
services:
  clinica:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - clinica
    depends_on:
      - db

  db:
    image: mysql:5.7
    networks:
      - clinica
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=clinica

networks:
  clinica:
    driver: bridge